### ISSUE TITLE
All the sawara's image has been lost

### ISSUE THREAD

**Issue by murimurikyu** [Ender-Wiggin2019/VTuber-Logos-Collection#17]
![Screenshot_20240512-005851](https://github.com/Ender-Wiggin2019/VTuber-Logos-Collection/assets/168010907/a12637b0-f538-40a5-a1a0-e7b9f4486dc2)

**Comment by xelab04** [comment]
Not the repo's owner. However, Sawaratsuki had to take her repo private due to (apparently, maybe lost in translation) licensing issues. Since this app refers to the images on her repo, it can't load them in.
Hopefully she will reupload the logos soon!

**Comment by Ender-Wiggin2019** [comment]
I currently use my forked repo for image backup. Though I don't know much about the license issue (i.e. can we display the images online? since I can still find all logos from Sawaratsuki's twitter account).

I add a license icon for each logo for a claim, hope it can work.

![picgo-2024-05-12-001060](https://github.com/Ender-Wiggin2019/VTuber-Logos-Collection/assets/49976407/7dc0f6ea-ef0a-4c69-89cc-a0e82a967a0d)
