### ISSUE TITLE
Still me... With the "dont know to upload" proplem

### ISSUE THREAD

**Issue by murimurikyu** [Ender-Wiggin2019/VTuber-Logos-Collection#19]
So i made thouse 
https://drive.google.com/drive/mobile/folders/13HGThol9SmYyBJ9D3D7-Lmr1P_drqNHU?usp=drive_link&fbclid=IwZXh0bgNhZW0CMTEAAR3PJ59iyxC1XGddqvxGFXhiYBTS1ggQAImSO84JKqkDM5zBDRGWY-V9SXU_aem_Aa2Mzlr1BdgF5pzkx0zlHdJGmTuyEtNVpQ-eXpzMcZ3KSUqB9uqt8KSluLTyjva8_6db1kXFGc-j9_utdvazvULR
And is there any way to it auto update when i add more on that google drive link?

**Comment by Ender-Wiggin2019** [comment]
Hi murimurikyu, IMO the best way is create a GitHub repo similar to [this](https://github.com/SAWARATSUKI/KawaiiLogos). And then some program can automatically (or semi-auto) update your logos

**Comment by murimurikyu** [comment]
https://github.com/murimurikyu/CuteVtubingThing
i made github repo, what's the next step

**Comment by Ender-Wiggin2019** [comment]
Sure, I will take a look

**Comment by murimurikyu** [comment]
Still dont know what to do next XD

**Comment by Ender-Wiggin2019** [comment]
I will upload these images when I have time. No worry XD

**Comment by murimurikyu** [comment]
Thanks yal
Do i need somekind of update mýelf when i upload new one or it just automaticaly update when i upload newone on  my repo?

**Comment by Ender-Wiggin2019** [comment]
Hi murimurikyu, if you can set up your repo similar to [this](https://github.com/SAWARATSUKI/KawaiiLogos) (folder -> image) then I can upload all your images once you change it. Otherwise I need to take a while to write some more code for this case.

Usually, I will fetch all upper-streaming repos frequently for this period. Later it will become an automatically task.

**Comment by murimurikyu** [comment]
okay i gonna do it now

**Comment by murimurikyu** [comment]
sorry but i tryed to make it in folder but some how it not working (i tryed to folow youtube guide) and end up with nuke all of old one. i has re upload it but still cant some how make it right
https://github.com/murimurikyu/CuteVtubingThing

**Comment by Ender-Wiggin2019** [comment]
Okay, then I'll help you with that and no need to upload folders. But you still need to rename all images (i.e. fb.png to Facebook.png) since the file name will be displayed on website later.

Btw, the advantage of folder-image structure is, you can have multiple images within each logo folder. Without folder, then it can only have one image for each logo.

**Comment by murimurikyu** [comment]
i has rename all the files
thanks u verry much

**Comment by murimurikyu** [comment]
so when i upload new files, it can automaticaly update without need to notice you to update it right?

**Comment by Ender-Wiggin2019** [comment]
Add. Not automatically yet, but can be updated with a simple click
