### ISSUE TITLE
IamSeries not update correctly

### ISSUE THREAD

**Issue by lolosssss** [Ender-Wiggin2019/VTuber-Logos-Collection#9]
There are four ImSeries logos, but only two in this collection.

**Comment by lolosssss** [comment]
Maybe just generate the new brand file every time [code](https://github.com/Ender-Wiggin2019/VTuber-Logos-Collection/blob/1d2529191995bb51acffaf36143b58f4f3b1b34a/generate/generate_brand_from_folder.js#L93C1-L93C60)

**Comment by Ender-Wiggin2019** [comment]
I see, previously I tried not to override so that I can directly modified the `brand.ts` such as add an alias or set a category.
In this case I may just try to modify it manually, because ImSeries is too customized (semantic meaning, special character such as `!`) for some automatically process.
**An extra process to detect whether we miss some images may be better I guess. Will put it in future plan.**
